FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD tekforce.jar /opt/tekforce/
EXPOSE 8080
WORKDIR /opt/tekforce/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "tekforce.jar"]
