FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD comcast.jar /opt/comcast/
EXPOSE 8080
WORKDIR /opt/comcast/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "comcast.jar"]
